### ISSUE TITLE
Ability to turn off stats reporting

### ISSUE THREAD

**Issue by mamoit** [revolucaodosbytes/ahoy-chrome#3]
There should be a way to toggle off website access reporting.

**Comment by rafaelcpalmeida** [comment]
We can look into it, I'm sure it won't be a big issue. I can add that option on the new Firefox extension and try to modify Chrome ASAP :+1:

**Comment by mamoit** [comment]
Can't wait for the ff version :smiley:

**Comment by rafaelcpalmeida** [comment]
It will be here https://github.com/revolucaodosbytes/ahoy-firefox :smile:

**Comment by mamoit** [comment]
:+1:

**Comment by vaurdan** [comment]
We've decided that we're not going to implement this. This is part of the service as it is, and adding an extra option will be adding another layer of complexity which is irrelevant for 99,99% of our current users.

**Comment by mamoit** [comment]
I do not think that's the right decision to make since your users are in big part privacy advocates.
But I understand that this is not a priority for you.

**Comment by vaurdan** [comment]
Yes, I understand what you mean. But as I mentioned, 99,99% of our users don't even care about sending the stats, and adding another button will be adding more complexity to the interface. Also the stats itself doesn't represent any privacy violation since it doesn't gather any personal information and it's useful for understanding and improving the service quality. 

Maybe, if we end up adding more features that will require a new settings panel we can think about this particular feature, but for the moment we don't think this is relevant enough.

**Comment by mamoit** [comment]
fair enough :+1:
